---
- name: "Running validate_arg_specs as a task"
  hosts: localhost
  gather_facts: false
  vars:
    category: "Misc"
    argument_spec_data:
      name: "the_arg_spec_data_for_validate_arg_specs_as_a_task"
      description: "EXPECTED FAILURE Validating the arg spec"
      argument_spec:
        some_int:
          type: "int"
          required: true
        some_str:
          type: "str"
          default: "blippyfoobar"
        some_choice:
          type: "str"
          choices:
            - "large"
            - "gigantic"
            - "extra gigantic"
          required: false
    provided_arguments:
      some_int: "does this count as an int"
      some_str: "hunter42"
      some_choice: "medium"
  tasks:
    - name: "EXPECTED FAILURE test validate_arg_spec"
      ignore_errors: true
      validate_arg_spec:
        argument_spec: "{{ argument_spec_data }}"
        provided_arguments: "{{ provided_arguments }}"
        validate_args_context:
          type: "standalone task"
          name: "test stuff"
          category: "{{ category }}"
      register: test_validate_arg_spec_result

    - name: show failed task result
      debug:
        var: test_validate_arg_spec_result

    - name: assert some_choice failed to decide
      assert:
        that:
          - "'value of some_choice must be one of: large, gigantic, extra gigantic, got: medium' in test_validate_arg_spec_result.argument_errors"
